### ISSUE TITLE
ARN Error  No Response

### ISSUE THREAD

**Issue by yanglichuan** [manolovn/trianglify#2]

**Comment by songzhw** [comment]
I run the app, and the phone is frozen. 

I took a look at the java heap, and found more than 68K objects of the "Point" Class(1280*270 phone). Hope this message will help you.

**Comment by songzhw** [comment]
I created a pull request to fix the ANR. Please see : https://github.com/manolovn/trianglify/pull/3

**Comment by manolovn** [comment]
Just one thing, fix checkstyle errors please https://travis-ci.org/manolovn/trianglify/builds/103576059
